### ISSUE TITLE
Ability to change z-index in skipto configuration

### ISSUE THREAD

**Issue by bryanjonker-illinois** [skipto-landmarks-headings/page-script-5#1]
Copy of https://github.com/paypal/skipto/issues/118

One of our users noted that the skip-to is not going above our menu. Is there a way we can set the z-index on the skip-to so we can ensure this doesn't happen?

Do we want to hardcode the z-index, have it in a configuration file, or give guidelines on how to fix it on a user's system?

**Comment by bryanjonker-illinois** [comment]
Sounds good. Should this be added to the README file?

**Comment by jongund** [comment]
You can now change the z-index using configuration:

```
<script>
var SkipToConfig =  {
  zIndex: '200000'   // default value is 100000
};
</script>
```
