### ISSUE TITLE
Keyboard shortcut doesn't work on 2019 french macbook pro

### ISSUE THREAD

**Issue by KuSh** [skipto-landmarks-headings/page-script-5#11]
Tested on https://www.w3.org/WAI/ARIA/apg/patterns/, trying Option+0 or Option+Shift+0 doesn't work

event.key value is "Ø" with Shift pressed, "ø" otherwise.

Perhaps using event.code which is Digit0 in both case could help ? Or it should be explained that it only work with a numerical pad

Regards,
KuSh

**Comment by jongund** [comment]
@KuSh 
I think I have fixed the bug, please try on the following website:
[https://accessibleit.disability.illinois.edu/](https://accessibleit.disability.illinois.edu/)

Let me know if it fixes the bug, if it does I will start the process of getting it updated on the ARIA APG website.

Thank you for reporting this issue.

**Comment by KuSh** [comment]
@jongund that works like a charm ! Thanks a lot for your time ❤️

**Comment by jongund** [comment]
@KuSh 
Your welcome.
Thank you for testing the fix.
