### ISSUE TITLE
skip-to not working when using custom components

### ISSUE THREAD

**Issue by bryanjonker-illinois** [skipto-landmarks-headings/page-script-5#2]
Copy of: https://github.com/paypal/skipto/issues/119

We started changing our website to use custom components. When we wrapped everything in the <il-page> component, the skip-to no longer registered any headings in the page. Also, tabbing did not show the skip-to link -- you had to be on Chrome and use Alt-0 to display it.

https://education.illinois.edu/
https://education.illinois.edu/about/mission-vision

**Comment by jongund** [comment]
Plan on adding that feature in version 6.0, which will require changes in configuration of how headings and landmarks are selected.
