### ISSUE TITLE
Landmark order in extension does not match order on webpage

### ISSUE THREAD

**Issue by rsgranne** [skipto-landmarks-headings/page-script-5#24]
I test extensions like this on a simple webpage I created at https://cdpn.io/pen/debug/GRxojVq. There are 4 landmarks on the page, in this order:

header (corresponding to Banner)
nav (corresponding to Navigation)
main (corresponding to Main)
footer (corresponding to Contentinfo)

However, when I activate the extension, it displays the order as:

Main
Navigation
Contentinfo
Banner

I was expecting that the order would instead be:

Banner
Navigation
Main
Contentinfo

I am using Brave on a Mac, but I can’t imagine that has anything to do with it.

Thanks!

**Comment by jongund** [comment]
Thank you for your feedback.
The order of the landmarks are in order of importance, not document order.
It would be a good idea to have an option for people to see them in document order.

**Comment by rsgranne** [comment]
I certainly wasn’t expecting them to be in order of importance, so yes, an option would be great!

**Comment by jongund** [comment]
@rsgranne 
I just submitted version 1.0.4 for review and it includes a option to list the landmarks in document order.
Please try it out when 1.0.4 becomes in a few days and let me know what you think.

**Comment by rsgranne** [comment]
This is great. It works well.

Thank you so much for this extension. I teach college courses about Web dev, & when I get to HTML landmarks, I am going to show them your extension. I really appreciate your work!

**Comment by jongund** [comment]
@rsgranne 
Have you ever tried AInspector tor for Firefox?
[AInpsector for Firefox](https://addons.mozilla.org/en-US/firefox/addon/ainspector-wcag/)
