### ISSUE TITLE
Hide the tiny gray box at the top of every webpage?

### ISSUE THREAD

**Issue by rsgranne** [skipto-landmarks-headings/page-script-5#25]
Now that the extension is installed, I’m seeing a tiny gray box at the top of every page. When I click on it, it expands so I can see Skip To Content (Option+0).

I’d like a way to hide that gray box. I take a lot of screenshots, & I don’t want to see that gray box in every one, & I also don’t want to have to disable & enable the extension constantly.

Related to that, it might be good to adopt the standard menu that appears when you click on a pinned extension. For virtually every other extension, when I left-click on the pinned icon, a menu appears enabling me to access features of the extension. When I right-click on the pinned icon, I get a menu for managing the extension. However, with this extension, left-clicking shows me the menu for managing the extension, which is not what I was expecting. 

I would suggest that left-clicking on the pinned icon instead gives me the reminder about clicking Option+0, which would therefore remove the need for the continual gray box, & to see the regular menu to manage the extension, I need to right-click.

I am using Brave on a Mac.

**Comment by jongund** [comment]
Thank you for your feedback.
The gray at the top is to help make the SkipTo.js discoverable by anyone.
It seems that this SkipTo.js is not viewed as helpful to all users by giving them an outline of the page. 
I will consider an option to fully hide the button.
I will be on vacation for.a few weeks, so I will work on these issues when I get back.

What is the primary reason you use of SkipTo.js extension?

**Comment by jongund** [comment]
I submitted a fix for SkipTo.js for Chrome version 1.0.2, it should be available in a few days to this issue.  Let me know if it worked.

**Comment by jongund** [comment]
Please note the extension is now named SkipTo.js for Chrome in the Chrome WebStore, which has a different URL than when it was mistakenly named SkipTo.js for Firefox in the chrome store.

**Comment by jongund** [comment]
@rsgranne 
Version 1.02 is available, note the change in name in the previous comment.  

Please let me know if it fixes this issue for you.

**Comment by jongund** [comment]
@rsgranne 
Have you had a chance to try out the change?

**Comment by rsgranne** [comment]
I did, & it all appears to work well! Thank you!

**Comment by jongund** [comment]
Would you mind adding your review to the current version?
https://chromewebstore.google.com/detail/skiptojs-for-chrome/mgmnhfooeifhicajoeoamlchoadbioof?hl=en
