### ISSUE TITLE
Change scroll behavior or give behavior options? 

### ISSUE THREAD

**Issue by bryanjonker-illinois** [skipto-landmarks-headings/page-script-5#26]
https://github.com/skipto-landmarks-headings/page-script-5/blob/main/src/highlightElement.js#L120 has the following line: 

`element.scrollIntoView({ behavior: 'smooth', block: 'start', inline: 'nearest' });`

Can we change the default to 'instant' and/or allow people change the behavior? 

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView#behavior

**Comment by bryanjonker-illinois** [comment]
This was brought up in the Explore with Hadi meeting today

**Comment by jongund** [comment]
@bryanjonker-illinois 
Thank you Brain for the references and comments.
I have updated the Illinois CDN with a version that disables the scrolling by default.
In version 5.6.2 there are options for either `smooth` or `instant` scrolling, which will useful for people using the browser extension version of SkipTo.js.   They will have configuration options for none, smooth or instant scrolling.
