### ISSUE TITLE
Pages with only h1 shows duplicate landmarks in skipto menu

### ISSUE THREAD

**Issue by leslies-illinois** [skipto-landmarks-headings/page-script-5#8]
Hi,
As part of my IADP course, I created a website and implemented the skipto script with it. I found that when I have an H2 (even one with display:none;) or lower heading on a page, the list of landmarks displayed correctly, but when I have a page with only an H1 heading the landmarks are duplicated. 

[Sample code available on Box](https://uofi.box.com/shared/static/5st0uryifji74si0m4mhdr8ad51vit6y.zip)

In this example, the index.html page displays the landmarks correctly in the skipto menu. The about.html and contactme.html pages do not have H2s and they show duplicates. To test this issue, I added an H2 to the about.html page and found it no longer displayed duplicates. If the H2 is updated to have a style of display:none, it still displays correctly. When the h2 is commented out or removed, then duplicates are displayed.

If you have questions, please let me know.

Thanks,
Leslie

**Comment by jongund** [comment]
@leslies-illinois 
Thanks for reporting this bug, I will look into right now.
